export const MessageConstants = {
    ADMIN: {
        LOGIN_SUCCESS: "Admin login successful.",
        LOGOUT_SUCCESS: "Admin logged out successfully.",
        BOOKING_FETCH_SUCCESS: "Bookings fetched successfully.",
    },
    USER: {
        BLOCK_SUCCESS: "User blocked successfully.",
        UNBLOCK_SUCCESS: "User unblocked successfully.",
        FETCH_SUCCESS: "Users fetched successfully.",
        PROFILE_UPDATE_SUCCESS: "User profile updated successfully.",
        PASSWORD_CHANGE_SUCCESS: "User password changed successfully.",
        LOGIN_SUCCESS: "login successful.",
        LOGOUT_SUCCESS: "logged out successfully.",
    },
    LAWYER: {
        APPROVE_SUCCESS: "Lawyer approved successfully.",
        REJECT_SUCCESS: "Lawyer rejected successfully.",
        BLOCK_SUCCESS: "Lawyer blocked successfully.",
        UNBLOCK_SUCCESS: "Lawyer unblocked successfully.",
        FETCH_SUCCESS: "Lawyers fetched successfully.",
        PROFILE_UPDATE_SUCCESS: "Lawyer profile updated successfully.",
        PASSWORD_CHANGE_SUCCESS: "Lawyer password changed successfully.",
        LOGIN_SUCCESS: "login successful.",
        LOGOUT_SUCCESS: "logged out successfully.",
        AVAILABILITY_UPDATE_SUCCESS: "Availability rules updated successfully.",
        AVAILABILITY_FETCH_SUCCESS: "Availability rules fetched successfully.",
        APPOINTMENTS_FETCH_SUCCESS: "Appointments fetched successfully.",
        EARNINGS_FETCH_SUCCESS: "Earnings statistics fetched successfully.",
        CASES_FETCH_SUCCESS: "Cases fetched successfully.",
        REVIEWS_FETCH_SUCCESS: "Reviews fetched successfully.",
    },
    SPECIALIZATION: {
        CREATE_SUCCESS: "Specialization created successfully.",
        UPDATE_SUCCESS: "Specialization updated successfully.",
        DELETE_SUCCESS: "Specialization deleted successfully.",
        FETCH_SUCCESS: "Specializations fetched successfully.",
    },
    SUBSCRIPTION: {
        CREATE_SUCCESS: "Subscription plan created successfully.",
        UPDATE_SUCCESS: "Subscription plan updated successfully.",
        DELETE_SUCCESS: "Subscription plan deleted successfully.",
        STATUS_UPDATE_SUCCESS: "Subscription status updated successfully.",
        FETCH_SUCCESS: "Subscription plans fetched successfully.",
        CURRENT_FETCH_SUCCESS: "Current subscription fetched successfully.",
        CHECKOUT_SESSION_CREATE_SUCCESS: "Checkout session created successfully.",
    },
    DASHBOARD: {
        STATS_FETCH_SUCCESS: "Dashboard statistics fetched successfully.",
    },
    PAYMENT: {
        PAYOUT_APPROVE_SUCCESS: "Payout approved successfully.",
        FETCH_SUCCESS: "Payouts fetched successfully.",
        WITHDRAWAL_REQUEST_SUCCESS: "Withdrawal request submitted successfully.",
    },
    BOOKING: {
        INITIATE_SUCCESS: "Booking payment initiated successfully.",
        CONFIRM_SUCCESS: "Booking confirmed successfully.",
        FETCH_SUCCESS: "User appointments fetched successfully.",
        CANCEL_SUCCESS: "Appointment cancelled successfully.",
    },
    REPOSITORY: {
        CREATE_ERROR: "Database error while creating document.",
        FIND_ERROR: "Database error while finding document.",
        FIND_BY_ID_ERROR: "Database error while finding document by ID.",
        UPDATE_ERROR: "Database error while updating document.",
        DELETE_ERROR: "Database error while deleting document.",
        FETCH_ERROR: "Database error while fetching documents.",
        COUNT_ERROR: "Database error while counting documents.",
        EXISTS_ERROR: "Database error while checking existence.",
        VERIFY_ERROR: "Database error while verifying.",
        EMAIL_FETCH_ERROR: "Database error while fetching by email.",
        PASSWORD_UPDATE_ERROR: "Database error while updating password.",
        VERIFICATION_SUBMISSION_ERROR: "Database error while marking verification submission.",
        PAGINATED_FETCH_ERROR: "Database error while fetching paginated records.",
        BLOCK_ERROR: "Database error while blocking.",
        UNBLOCK_ERROR: "Database error while unblocking.",
        APPROVE_ERROR: "Database error while approving.",
        REJECT_ERROR: "Database error while rejecting.",
        PROFILE_FETCH_ERROR: "Database error while fetching profile.",
        PROFILE_UPDATE_ERROR: "Database error while updating profile.",
        GOOGLE_ID_UPDATE_ERROR: "Database error while updating googleId.",
        SUBSCRIPTION_UPDATE_ERROR: "Database error while updating subscription status.",
        WALLET_UPDATE_ERROR: "Database error while updating wallet balance.",
        ACTIVE_FETCH_ERROR: "Database error while fetching active record.",
        SESSION_FETCH_ERROR: "Database error while fetching record by session ID.",
        CALL_STATUS_UPDATE_ERROR: "Database error while updating call status.",
        EARNINGS_STATS_ERROR: "Database error while calculating earnings stats.",
        TRANSACTION_FETCH_ERROR: "Database error while fetching transactions.",
        WITHDRAWAL_CREATE_ERROR: "Database error while creating withdrawal request.",
        INTERNAL_SERVER_ERROR: "Internal server error occurred.",
    },
    COMMON: {
        UNAUTHORIZED: "Unauthorized access.",
        BAD_REQUEST: "Invalid request.",
        INTERNAL_ERROR: "An unexpected error occurred.",
        SUCCESS: "Operation successful.",
    }
} as const;
