export class Booking {
    constructor(
        public id: string,
        public userId: string,
        public lawyerId: string,
        public date: string,
        public startTime: string,
        public endTime: string,
        public consultationFee: number,
        public status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'rejected' | 'follow-up',
        public paymentStatus: 'pending' | 'paid' | 'failed',
        public paymentId?: string,
        public stripeSessionId?: string,
        public description?: string,
        public userName?: string,
        public cancellationReason?: string,
        public lawyerName?: string,
        public refundAmount?: number,
        public refundStatus?: 'none' | 'full' | 'partial',
        public isCallActive?: boolean,
        public lawyerJoined?: boolean,
        public commissionPercent: number = 0,
        public lawyerFeedback?: string,
        public bookingId?: string,
        public createdAt?: Date,
        public followUpType: 'none' | 'specific' | 'deadline' = 'none',
        public followUpDate?: string,
        public followUpTime?: string,
        public followUpStatus: 'cancelled' | 'pending' | 'booked' | 'none' = 'none',
        public parentBookingId?: string,
        public followUpSlotId?: string
    ) { }
}
